services:
  prefect:
    image: prefect-app
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
      - "4201:4201"
      - "4202:4202"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data

volumes:
  minio-data:
