CREATE TABLE stg_weather_data (
    weather_id              INTEGER,
    weather_main            VARCHAR(50),
    weather_description     VARCHAR(100),
    weather_icon            VARCHAR(10),
    visibility              INTEGER,
    dt                      TIMESTAMPTZ,
    city_id                 BIGINT,
    city_name               VARCHAR(100),
    city_lon                DOUBLE PRECISION,
    city_lat                DOUBLE PRECISION,
    city_country            VARCHAR(10),
    city_timezone           INTEGER,
    sunrise                 TIMESTAMPTZ,
    sunset                  TIMESTAMPTZ,
    main_temp               DOUBLE PRECISION,
    main_feels_like         DOUBLE PRECISION,
    main_temp_min           DOUBLE PRECISION,
    main_temp_max           DOUBLE PRECISION,
    main_pressure           DOUBLE PRECISION,
    main_grnd_level         DOUBLE PRECISION,
    main_humidity           INTEGER,
    main_sea_level          DOUBLE PRECISION,
    wind_speed              DOUBLE PRECISION,
    wind_deg                INTEGER,
    clouds_all              INTEGER
);